#Docker image to build and run tests of the Scala project
image: hseeberger/scala-sbt:8u302_1.5.5_2.13.6

pipelines:

  default:
    - step:
        name: Build and Test
        caches:
          - sbt
        script:
          - sbt clean compile test

  pull-requests:
    '**':
      - step:
          name: Run tests for all pull requests
          script:
            - sbt clean compile test
