# Use the official OpenJDK 8 image as the base image for the pipeline
image: openjdk:8

pipelines:
 branches:
    # Define the pipeline to run on all branches except the master branch
    '**':
      - step:
          name: Run tests
          script:
            # Install sbt, the build tool for Scala
            - curl -sL "https://piccolo.link/sbt-1.5.5.tgz" | tar -xz -C /usr/share
            - update-alternatives --install /usr/bin/sbt sbt /usr/share/sbt/bin/sbt 1
            # Run the tests using sbt
            - sbt test
  # Define the pipeline to run on the master branch
  branches:
    master:
      - step:
          name: Prevent direct merges to master
          script:
            # Check if the commit message contains the "[skip ci]" keyword
            - if [[ $(git log -n 1 --pretty=format:%s) != *"[skip ci]"* ]]; then exit 1; fi