# Will be deleted after account upgrade to team ro Enterprise account.
name: Prevent direct pushes to master

on:
  push:
    branches:
      - main

jobs:
  prevent-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is allowed
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ] && [ "${{ github.event_name }}" = "push" ]; then
            echo "Direct pushes to master are not allowed. Please open a pull request instead.";
            exit 1;
          fi
