name: Lighthouse Tests
# triggers for the workflow
on:
  [push, pull_request]


jobs:
  build:
    # job should run on a Ubuntu 20.04 virtual machine
    runs-on: ubuntu-latest

    steps:
    # check out the code from the repository
    - name: Checkout code
    - uses: actions/checkout@v3
    
    # installs Java 8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: 'sbt'
        
    # run the project's tests
    - name: Run tests
      run: sbt test

