name: Lighthouse Tests

on:
  [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: 'sbt'

    - name: Run tests
      run: sbt test

  # Will be deleted when organization account is upgraded to a GitHub Team or Enterprise account.
  prevent-push:

    runs-on: ubuntu-latest

    steps:

      - name: Check if push is allowed
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Direct pushes to main are not allowed. Please open a pull request instead.";
            exit 1;
          fi